// <auto-generated />
using System;
using GamesCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GamesCollection.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200119185616_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GamesCollection.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "US",
                            Name = "Take Two Interactive",
                            Website = "https://take2games.com"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "US",
                            Name = "Xbox Game Studios",
                            Website = "https://xbox.com/en-US/xbox-game-studios/"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "PL",
                            Name = "CD Projekt",
                            Website = "https://cdprojekt.com/"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "US",
                            Name = "Electronic Arts",
                            Website = "https://ea.com/"
                        },
                        new
                        {
                            Id = 5,
                            CountryCode = "US",
                            Name = "BioWare",
                            ParentId = 3,
                            Website = "https://bioware.com/"
                        },
                        new
                        {
                            Id = 6,
                            CountryCode = "US",
                            Name = "ZeniMax Media",
                            Website = "https://zenimax.com/"
                        },
                        new
                        {
                            Id = 7,
                            CountryCode = "FR",
                            Name = "Arkane Studios",
                            ParentId = 6,
                            Website = "https://arkane-studios.com/"
                        },
                        new
                        {
                            Id = 8,
                            CountryCode = "US",
                            Name = "Bethesda Softworks",
                            ParentId = 6,
                            Website = "https://bethesda.com/"
                        },
                        new
                        {
                            Id = 9,
                            CountryCode = "US",
                            Name = "id Software",
                            ParentId = 6,
                            Website = "https://idsoftware.com/"
                        },
                        new
                        {
                            Id = 10,
                            CountryCode = "US",
                            Name = "ZeniMax Online Studios",
                            ParentId = 6,
                            Website = "https://zenimaxonline.com/"
                        },
                        new
                        {
                            Id = 11,
                            CountryCode = "FR",
                            Name = "UbiSoft",
                            Website = "https://ubisoft.com/"
                        },
                        new
                        {
                            Id = 12,
                            CountryCode = "CA",
                            Name = "UbiSoft Montreal",
                            ParentId = 11,
                            Website = "https://montreal.ubisoft.com/"
                        },
                        new
                        {
                            Id = 13,
                            CountryCode = "US",
                            Name = "2K Games",
                            ParentId = 1,
                            Website = "https://2k.com"
                        },
                        new
                        {
                            Id = 14,
                            CountryCode = "US",
                            Name = "Rockstar Games",
                            ParentId = 1,
                            Website = "https://rockstargames.com"
                        },
                        new
                        {
                            Id = 15,
                            CountryCode = "US",
                            Name = "Firaxis Games",
                            ParentId = 13,
                            Website = "https://www.firaxis.com/"
                        },
                        new
                        {
                            Id = 16,
                            CountryCode = "US",
                            Name = "Obsidian Entertainment",
                            ParentId = 2,
                            Website = "https://www.firaxis.com/"
                        },
                        new
                        {
                            Id = 17,
                            CountryCode = "SE",
                            Name = "Paradox Interactive",
                            Website = "https://www.paradoxplaza.com/"
                        },
                        new
                        {
                            Id = 18,
                            CountryCode = "US",
                            Name = "Hardsuit Labs",
                            ParentId = 17,
                            Website = "https://www.hardsuitlabs.com/"
                        },
                        new
                        {
                            Id = 19,
                            CountryCode = "FR",
                            Name = "Focus Home Interactive",
                            Website = "http://focus-home.com/"
                        },
                        new
                        {
                            Id = 20,
                            CountryCode = "FR",
                            Name = "Asobo Studio",
                            ParentId = 19,
                            Website = "http://www.asobostudio.com/"
                        },
                        new
                        {
                            Id = 21,
                            CountryCode = "GE",
                            Name = "Deep Silver",
                            Website = "https://www.deepsilver.com/"
                        },
                        new
                        {
                            Id = 22,
                            CountryCode = "CZ",
                            Name = "Bohemia Interactive Studio",
                            Website = "http://www.bohemia.net/"
                        },
                        new
                        {
                            Id = 23,
                            CountryCode = "CZ",
                            Name = "Warhorse Studios",
                            ParentId = 21,
                            Website = "http://www.warhorsestudios.cz/"
                        },
                        new
                        {
                            Id = 24,
                            CountryCode = "US",
                            Name = "Facebook",
                            Website = "http://www.facebook.com/"
                        },
                        new
                        {
                            Id = 25,
                            CountryCode = "CZ",
                            Name = "Beat Games",
                            ParentId = 25,
                            Website = "http://www.beatgames/"
                        },
                        new
                        {
                            Id = 26,
                            CountryCode = "PL",
                            Name = "CD Projekt RED",
                            ParentId = 3,
                            Website = "https://en.cdprojektred.com/"
                        },
                        new
                        {
                            Id = 27,
                            CountryCode = "US",
                            Name = "Steam",
                            Website = "https://www.steampowered.com/"
                        });
                });

            modelBuilder.Entity("GamesCollection.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YouTubeChannel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "<p>In Cyberpunk 2077 you play as V — a hired gun on the rise — and you just got your first serious contract. In a world of cyberenhanced street warriors, tech-savvy netrunners and corporate lifehackers, today you take your first step towards becoming an urban legend.</p>",
                            DeveloperId = 26,
                            Name = "Cyberpunk 2077",
                            PublisherId = 3,
                            Website = "https://www.cyberpunk.net/",
                            YouTubeChannel = "https://www.youtube.com/user/CyberPunkGame"
                        },
                        new
                        {
                            Id = 2,
                            Description = "<p>DayZ is a survival video game developed and published by Bohemia Interactive. It is the standalone successor of the mod of the same name. Following a five-year long early access period for Windows, the game was officially released in December 2018, and was released for the Xbox One and PlayStation 4 in 2019.</p>",
                            DeveloperId = 22,
                            Name = "DayZ",
                            PublisherId = 22,
                            Website = "https://www.bohemia.net/games/dayz",
                            YouTubeChannel = "https://www.youtube.com/user/BohemiaInteract"
                        });
                });

            modelBuilder.Entity("GamesCollection.Models.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 12
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 3
                        });
                });

            modelBuilder.Entity("GamesCollection.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Role-playing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shooter"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Platform"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Simulator"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Turn-based Strategy"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Real time Strategy"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Stealth"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Multiplayer"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Massive Multiplayer"
                        });
                });

            modelBuilder.Entity("GamesCollection.Models.Company", b =>
                {
                    b.HasOne("GamesCollection.Models.Company", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("GamesCollection.Models.Game", b =>
                {
                    b.HasOne("GamesCollection.Models.Company", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesCollection.Models.Company", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GamesCollection.Models.GameGenre", b =>
                {
                    b.HasOne("GamesCollection.Models.Game", "Game")
                        .WithMany("Genres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesCollection.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
